include:
  - board: nice_nano_v2
    shield: icarus_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: icarus_right
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
